services:
  onlinebookstoreapi:
    image: ${DOCKER_REGISTRY-}onlinebookstoreapi
    build:
      context: .
      dockerfile: OnlineBookstoreAPI/Dockerfile

  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_DATABASE: BookstoreDb 

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: S3cr3tP4sSw0rd#123
      MYSQL_DATABASE: BookstoreDb 
      MYSQL_USER: sa
      MYSQL_PASSWORD: S3cr3tP4sSw0rd#123

  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./init-redis.sh:/init-redis.sh
    command: ["bash", "/init-redis.sh"]

volumes:
  mongodb_data:
  mysql_data:
  redis_data:
